config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  resources :project_participants
  resources :registrations#, only: [:create]
  resources :sessions#, only: [:create]
  resources :projects
  root "home_pages#index"
  get '/logout', to: 'sessions#destroy', as: :logout
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :project_participants
  has_many :users, through: :project_participants
  belongs_to :propietario, class_name: 'User', foreign_key: :user_id
  validates_presence_of :title, :status, :slug
  validates_uniqueness_of :slug

  enum status: { active: 0, closed: 1, hold: 2 }

  after_create_commit :create_project_participant


  def create_project_participant
    ProjectParticipant.create(role: 0, status:1, project_id: self.id, user_id: propietario.id)
  end

  def missing_participants
    User.where.not(id: users.select(:id))
  end

  def propietario?(user)
    propietario == user
  end


end

app/models/project_participant.rb
class ProjectParticipant < ApplicationRecord
  belongs_to :user
  belongs_to :project
  enum role: { propietario: 0, administrador: 1, miembro: 2 }
  enum status: { pending: 0, accepted: 1, declined: 3 }

  validates_presence_of :role
end

app/models/user.rb
class User < ApplicationRecord
  has_many :projects
  has_many :project_participants
  validates_presence_of :name, :username
  validates_uniqueness_of :username
  validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/ }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :user_signed_in?

  def user_signed_in?
    !current_user.nil?
  end

  def current_user
    return unless session[:email]

    @current_user ||= User.find_by(email: session[:email])
  end

  def turbo_error_message(instance)
    render turbo_stream: turbo_stream.replace('error_message', partial: 'shared/error_message',
                                              locals: { message: instance.errors.full_messages.to_sentence })
  end

  def turbo_message(message)
    render turbo_stream: turbo_stream.replace('error_message', partial: 'shared/error_message',
                                              locals: { message: })
  end

end

app/controllers/home_pages_controller.rb
class HomePagesController < ApplicationController
  def index
    @hello = 'HELLO'
  end
end

app/controllers/project_participants_controller.rb
class ProjectParticipantsController < ApplicationController
  before_action :set_project_participants, only: [:update]

  def index
  end

  def create
    @project_participant = ProjectParticipant.new(project_participant_params)
    if @project_participant.save
      render turbo_stream: turbo_stream.remove("user_#{@project_participant.user.id}")
    else
      turbo_error_message(@project_participant)
    end
  end

  def show
  end

  def update
    if @project_participant.update(status: 1)
      render turbo_stream: turbo_stream.replace("project_participant_#{@project_participant.id}",
                                                partial: 'projects/project',
                                                locals: { project_participant: @project_participant, project: @project_participant.project}

                                                )
    else

    end
  end

  private

  def set_project_participants
    @project_participant = ProjectParticipant.find(params[:id])
  end

  def project_participant_params
    params.require(:project_participant).permit(:user_id, :project_id).merge(role: params[:project_participant][:role].to_i)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show]
  def index
    @project = Project.new
    @project_participants = current_user.project_participants
  end

  def show
    @project_participant = ProjectParticipant.find_by(user_id: current_user.id,
                                              project_id: @project.id)
    @users_emails = @project.missing_participants
  end

  def create
    @project = Project.new(projects_params)

    if @project.save
      redirect_to projects_path
    else
      turbo_error_message(@projects)
    end
  end

  private

  def set_project
    @project = Project.find_by(slug: params[:id])
  end

  def projects_params
    params.require(:project).permit(:title, :slug, :description).merge(user_id: current_user.id)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def index
    @user = User.new
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:email] = @user.email
      redirect_to root_path
    else
      turbo_error_message(@user)
    end

  end

  private

  def user_params
    params.require(:user).permit(:name, :username, :email)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = find_user_by_email
    if user.present?
      session[:email] = user.email
      redirect_to root_path
    else
      turbo_message('User not Found')
    end
  end

  def destroy
    session[:email] = nil
    redirect_to root_path
  end

  def find_user_by_email
    User.find_by(email: params[:email])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def close_btn
    base = 'fa-solid fa-xmark'
    content_tag(:i, '', class: base)
  end

  def project_participant_roles(project_participant)
    roles = case project_participant.role
            when 'propietario'
              ProjectParticipant.roles.except('propietario')
            when 'administrador'
              ProjectParticipant.roles.slice('miembro')
            else
              {} # Return an empty hash if there are no roles to display
            end
    roles.map { |key, value| [key.to_s.humanize, value] }.reverse
  end
end

app/helpers/home_pages_helper.rb
module HomePagesHelper
end

app/helpers/project_participants_helper.rb
module ProjectParticipantsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home_pages/index.html.erb
<h1>
	<%= @hello %>
</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gestion</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= turbo_frame_tag 'error_message' %>
    <div class="mt-5 mx-3">
      <%= yield %>
    </div>
  </body>
</html>

app/views/project_participants/create.html.erb
<h1>ProjectParticipants#create</h1>
<p>Find me in app/views/project_participants/create.html.erb</p>

app/views/project_participants/index.html.erb
<h1>ProjectParticipants#index</h1>
<p>Find me in app/views/project_participants/index.html.erb</p>

app/views/project_participants/show.html.erb
<h1>ProjectParticipants#show</h1>
<p>Find me in app/views/project_participants/show.html.erb</p>

app/views/projects/_form.html.erb
<%= form_with model: @project, local: true do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :slug %>
    <%= f.text_field :slug %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div class="card" style="width: 18rem;" id="<%= dom_id project_participant  %>">
  <div class="card-body">
    <h5 class="card-title">
      <% if project_participant.status == 'pending' %>
        <%= button_to "Aceptar Invitacion #{project_participant.role} ", project_participant_path(project_participant), method: :patch %>
        <div>
          <%= project.title %>
          <p>Owner: <%=  project.propietario.name %></p>
        </div>
        <% else %>
          <%= link_to project.title, project_path(project.slug) %>
        <% end %>
    </h5>
    <p class="card-text">
    <%= project.description %>
    </p>
  </div>
</div>

app/views/projects/_project_details.html.erb
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">
      <%= project.title %>
    </h5>
  </div>
</div>

<div class="d-flex flex-wrap gap-3 mt-5">
  <% @users_emails.each do |user| %>
    <%= render 'user_invitation', user: user, project_participant: @project_participant  %>
  <% end %>
</div>

<div>
  <h4>Participantes del curso</h4>
  <div>
    <% project.project_participants.each do |project_participant| %>
      <% if project_participant.status == 'accepted'  %>
      <div>
        <%= project_participant.user.name %>
        <%= project_participant.role %>
      </div>
        <% end %>
    <%end %>
  </div>
</div>

app/views/projects/_user_invitation.html.erb
<div id="<%= dom_id(user) %>" class="card p-3" style="width: 18rem;" >
  <%= user.name %>
  <%= user.email %>
  <%= form_with model: ProjectParticipant.new, url: project_participants_path do |f| %>
    <%= f.select :role, options_for_select(project_participant_roles(project_participant)) %>
    <%= f.hidden_field :project_id, value: project_participant.project.id %>
    <%= f.hidden_field :user_id, value: user.id  %>
    <%= f.submit 'Invite' %>
  <% end %>
</div>

app/views/projects/index.html.erb
<div>

  <div>
  <%= render 'form', project: @project %>
  </div>

  <div id="projects">
    <% @project_participants.each do | project_participant| %>
      <%= render 'project', project: project_participant.project, project_participant: project_participant %>
    <% end %>
  </div>
</div>

app/views/projects/show.html.erb
<%= render 'project_details', project: @project %>

app/views/shared/_error_message.html.erb
<%= turbo_frame_tag 'error_message' do %>
  <div data-controller="error-message">
    <div data-error-message-target="msg" class="error__message">
      <div class="px-2">
        <%= message %>
      </div>
      <%= link_to close_btn, '', data: {
        action: 'error-message#close_error_message'
      }, class: 'px-3' %>
    </div>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light bg-light">
  <%= link_to 'Gerencia', root_path %>
  <div>

    <% if user_signed_in? %>
      <p>Welcome <%= current_user.name %></p>
      <%= link_to 'My Projects', projects_path %>
      <%= link_to 'Log Out', logout_path %>
    <% else %>
      <%= link_to 'Register', registrations_path  %>
      <%= link_to 'Log In', sessions_path  %>
    <% end %>

  </div>
</nav>